using System.Linq.Expressions;
using Vora.Application.Libraries.ViewModels;
using Vora.Application.Media.Dtos;
using Vora.Application.Media.ViewModels;
using Vora.Domain.Entities.Actors;
using Vora.Domain.Entities.Media;

namespace Vora.Application.Media;

public interface IMediaRepository
{
    Task<MediaMatchInfoDto?> GetMediaMatchInfoAsync(Guid mediaItemId);
    Task<List<Guid>> GetEpisodeIdsForSeasonAsync(Guid seasonId);
    Task<List<Guid>> GetEpisodeIdsForShowAsync(Guid tvShowId);
    Task<Guid?> GetMovieIdByTitleAndYearAsync(string title, int? year, Guid libraryId);
    Task<Guid?> GetMovieIdByExternalIdAsync(string? tmdbId, string? imdbId, Guid libraryId);
    Task<Guid?> GetTvShowIdByTitleAndYearAsync(string title, int? year, Guid libraryId);
    Task<Guid?> GetTvShowIdByExternalIdAsync(string? tmdbId, string? imdbId, Guid libraryId);
    Task<Guid?> GetSeasonIdByNumberAsync(Guid tvShowId, int seasonNumber);
    Task<Guid?> GetEpisodeIdByNumberAsync(Guid seasonId, int episodeNumber);
    Task<List<Guid>> GetMediaIdsByExternalIdsAsync(List<string> tmdbIds, List<string> imdbIds);
    Task<CollectionMatchCandidatesDto> GetCollectionMatchCandidatesAsync(Guid? libraryId);
    Task<Dictionary<Guid, SeasonShowInfoDto>> GetSeasonShowInfoAsync(IReadOnlyCollection<Guid> seasonIds);
    Task<HashSet<string>> GetExistingLibraryPathsAsync(Guid libraryId);
    Task<List<string>> GetLibraryItemFilePathsAsync(Guid libraryId);
    Task<IEnumerable<Guid>> GetAllMediaItemIdsByLibraryAsync(Guid libraryId);
    Task<List<string>> GetMediaFilePathsAsync(Guid mediaItemId);
    Task<Dictionary<Guid, string>> GetDisplayTitlesByIdsAsync(IReadOnlyCollection<Guid> ids);
    Task<T?> GetProjectedAsync<T>(Guid id, Expression<Func<MediaItem, T>> projection, bool hasAllAccess = true, List<Guid>? allowedLibs = null, bool hasAllRatings = true, List<string>? allowedMovieRatings = null, List<string>? allowedTvRatings = null, bool blockUnrated = false);
    Task<IEnumerable<T>> GetAllProjectedAsync<T>(Expression<Func<MediaItem, T>> projection, Guid? libraryId = null, string? libraryType = null, bool hasAllAccess = true, List<Guid>? allowedLibs = null, bool hasAllRatings = true, List<string>? allowedMovieRatings = null, List<string>? allowedTvRatings = null, bool blockUnrated = false);
    Task<MediaItem?> GetForAnalysisAsync(Guid id);
    Task<MediaItem?> GetForPosterOverlayAsync(Guid id);
    Task<MediaItem?> GetForMetadataSyncAsync(Guid id);
    Task<IEnumerable<Guid>> GetMediaIdsMissingMetadataAsync(Guid libraryId);
    Task<IEnumerable<Guid>> GetMediaIdsMissingArtworkAsync(Guid libraryId);
    Task<IEnumerable<Guid>> GetMediaIdsMissingRatingsAsync(Guid libraryId);
    Task<List<Guid>> GetMediaIdsMissingTvdbIdAsync();
    Task<MediaItem?> GetForBasicUpdateAsync(Guid id);
    Task SyncMediaTracksAsync(Guid mediaPartId, List<MediaVideoTrack> incomingVideo, List<MediaAudioTrack> incomingAudio, List<MediaSubtitleTrack> incomingSubtitles);
    Task ReplaceMarkersAsync(Guid mediaItemId, IEnumerable<MediaItemMarker> markers);
    Task<List<MediaItemMarker>> GetMarkersForSeasonAsync(Guid seasonId);
    Task<List<MediaItemMarker>> GetMarkersAsync(Guid mediaItemId);
    Task<(bool MidStinger, bool PostStinger)> GetStingerFlagsAsync(Guid mediaItemId);
    Task<MarkerCoverageVM> GetMarkerCoverageAsync(Guid libraryId);
    Task<(int Total, int WithThumbnails)> GetVideoThumbnailCoverageAsync(Guid libraryId);
    Task<bool> AreMarkersLockedAsync(Guid mediaItemId);
    Task SetMarkersLockedAsync(Guid mediaItemId, bool locked);
    Task<bool> AreThumbnailsLockedAsync(Guid mediaItemId);
    Task SetThumbnailsLockedAsync(Guid mediaItemId, bool locked);
    Task UpdateMediaItemAsync(MediaItem item);
    Task SaveChangesAsync();
    Task AddMediaItemAsync(MediaItem item);
    Task AddMediaVideosAsync(IEnumerable<MediaVideo> videos);
    Task RemoveMediaVideosAsync(IEnumerable<MediaVideo> videos);
    Task AddMediaExtraAsync(MediaExtra extra);
    Task DeleteMediaByFilePathAsync(string filePath);
    Task MarkMediaMissingByFilePathAsync(string filePath);
    Task<List<TrashMediaItemVM>> GetMissingMediaAsync();
    Task<List<Guid>> GetExpiredMissingMediaIdsAsync(DateTime cutoffUtc);
    Task RestoreMissingMediaAsync(Guid id);
    Task DeleteMediaItemAsync(Guid id);
    Task AddMediaPartAsync(MediaPart part);
    Task SyncItemEditionFromPartsAsync(Guid mediaItemId);
    Task AddMediaCastMembersAsync(IEnumerable<MediaCastMember> castMembers);
    Task RemoveMediaCastMembersAsync(IEnumerable<MediaCastMember> castMembers);
    Task SetMediaCompaniesAsync(Guid mediaItemId, IEnumerable<int> companyIds);
    Task SetMediaCountriesAsync(Guid mediaItemId, IEnumerable<string> countryIsoCodes);
    Task SetMediaGenresAsync(Guid mediaItemId, IEnumerable<int> genreIds);
    Task SetTvNetworksAsync(Guid tvShowId, IEnumerable<int> networkIds);
    Task<bool> MediaExistsByExternalIdAsync(string externalId, string type);
    Task<HashSet<string>> GetExistingExternalIdsAsync(IEnumerable<string> externalIds, string type);
    Task<Dictionary<string, Guid>> GetLibraryIdsByTmdbIdsAsync(IEnumerable<string> tmdbIds);
    Task<List<MediaItem>> GetItemsPendingOverlayGenerationAsync(Guid libraryId, DateTime maxTemplateUpdatedDate);
    Task<bool> AnyItemHasOverlayAppliedAsync(Guid libraryId);
    Task<HashSet<string>> GetReferencedOverlayFileNamesAsync();
    Task<string?> GetParentContentRatingAsync(Guid mediaItemId);
}