<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Vora.Application\Vora.Application.csproj" />
    <ProjectReference Include="..\..\src\Vora.Domain\Vora.Domain.csproj" />
    <ProjectReference Include="..\..\src\Vora.Plugins\Vora.Plugins.csproj" />
  </ItemGroup>

</Project>
